// <auto-generated />
namespace OnlineRezervacijaBioskopskihKarata.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_image_to_projection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_image_to_projection));
        
        string IMigrationMetadata.Id
        {
            get { return "202101121302405_add_image_to_projection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
